# Generated by Django 3.0 on 2022-10-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20221023_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.IntegerField(verbose_name='OTP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pattern_order',
            field=models.CharField(max_length=3, verbose_name='Sequence'),
        ),
    ]
