# Generated by Django 3.0 on 2022-10-24 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20221023_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
