# Generated by Django 3.0 on 2022-10-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_temp_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pattern_order',
            field=models.CharField(max_length=3, null=True, verbose_name='Sequence'),
        ),
    ]
