# Generated by Django 3.0 on 2022-10-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20221024_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.IntegerField(null=True, verbose_name='OTP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pattern_order',
            field=models.CharField(max_length=3, verbose_name='Sequence'),
        ),
    ]
